// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7541.RocketBot;

import org.usfirst.frc7541.RocketBot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc7541.RocketBot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick joystickDrive;
    public JoystickButton armUpButton;
    public JoystickButton armDownButton;
    public JoystickButton extenderOut;
    public JoystickButton extenderIn;
    public JoystickButton rotatorLeft;
    public JoystickButton rotatorForward;
    public JoystickButton rotatorRight;
    public Joystick joystickOperator;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystickOperator = new Joystick(1);
        
        rotatorRight = new JoystickButton(joystickOperator, 7);
        rotatorRight.whenPressed(new RotatorRotateRight());
        rotatorForward = new JoystickButton(joystickOperator, 5);
        rotatorForward.whenPressed(new RotatorRotateForward());
        rotatorLeft = new JoystickButton(joystickOperator, 6);
        rotatorLeft.whenPressed(new RotatorRotateLeft());
        extenderIn = new JoystickButton(joystickOperator, 4);
        extenderIn.whenPressed(new ExtenderRetractCommand());
        extenderOut = new JoystickButton(joystickOperator, 3);
        extenderOut.whenPressed(new ExtenderExtendCommand());
        armDownButton = new JoystickButton(joystickOperator, 2);
        armDownButton.whenPressed(new ArmDown());
        armUpButton = new JoystickButton(joystickOperator, 1);
        armUpButton.whenPressed(new ArmUp());
        joystickDrive = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("TeleOpDriveCommand", new TeleOpDriveCommand());
        SmartDashboard.putData("ExtenderExtendCommand", new ExtenderExtendCommand());
        SmartDashboard.putData("ExtenderRetractCommand", new ExtenderRetractCommand());
        SmartDashboard.putData("RotatorRotateLeft", new RotatorRotateLeft());
        SmartDashboard.putData("RotatorRotateRight", new RotatorRotateRight());
        SmartDashboard.putData("RotatorRotateForward", new RotatorRotateForward());
        SmartDashboard.putData("ArmUp", new ArmUp());
        SmartDashboard.putData("ArmDown", new ArmDown());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystickDrive() {
        return joystickDrive;
    }

    public Joystick getJoystickOperator() {
        return joystickOperator;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

