// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc7541.RocketBot.commands;

import org.usfirst.frc7541.RocketBot.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

public class AutonomousCommand extends CommandGroup {

    public AutonomousCommand() {
        //addSequential(new DriveToLineCommandGroup());
        addSequential(new DriveStraightCommand(132));
        addParallel(new RotatorRotate(-90));
        addSequential(new DriveSpinToCommand(270));
        addSequential(new DriveStraightCommand(20));
        addSequential(new DriveToLineCommandGroup());
        // addSequential(new RotatorRotate(-90));
        // addSequential(new ExtenderTimedCommand(0.5)); // Stops after 0.5 seconds
    }

    @Override
    protected void initialize() {
        Robot.driveTrain.resetHeading();
        super.initialize();
    }
}
